<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class EstablishmentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('establishments')->insert([
            [
                'name' => 'Beit Sitti',
                'type' => 'restaurant',
                'address' => 'Maktab Anbar, Al-Qaymariya, Damascus',
                'city' => 'Damascus',
                'location' => 'Maktab Anbar (Old City - Al-Qaymariya), Damascus',
                'lat' => 33.5059000,
                'lon' => 36.3057000,
                'contact_phone' => '+963944973241',
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['reservations' => true, 'shisha' => true, 'family_friendly' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Naranj Restaurant',
                'type' => 'restaurant',
                'address' => 'Straight Street (Al-Shāriʿ al-Mustaqīm) — Old City (near Roman Arch), Damascus',
                'city' => 'Damascus',
                'location' => 'Old City — Straight Street, near Roman Arch',
                'lat' => 33.5055000,
                'lon' => 36.3068000,
                'contact_phone' => '+963115413444',
                'contact_email' => 'marketing@gemini-sy.com',
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['reservations' => true, 'roof_terrace' => true, 'shisha' => true]),
                'website' => null,
                'facebook' => 'https://www.facebook.com/NaranjSyr/',
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Beit Jabri (Jabri House)',
                'type' => 'restaurant',
                'address' => '14 Sharia-as-Sawaf (As Sawwaf), Old City, Damascus',
                'city' => 'Damascus',
                'location' => 'Old City — As Sawwaf alley (historic Damascene house)',
                'lat' => 33.5058000,
                'lon' => 36.3059000,
                'contact_phone' => '+963115443200',
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['traditional' => true, 'reservations' => true, 'family_friendly' => true]),
                'website' => 'http://www.jabrihouse.com',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Four Seasons Hotel Damascus',
                'type' => 'hotel',
                'address' => 'Shukri Al Quatli St, P.O. Box 6311, Damascus',
                'city' => 'Damascus',
                'location' => 'Central Damascus — Shukri Al Quatli Street',
                'lat' => 33.5083330,
                'lon' => 36.2879990,
                'contact_phone' => '+963113391000',
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['parking' => true, 'spa' => true, 'pool' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Al-Mouwasat University Hospital',
                'type' => 'medical',
                'address' => 'Mazzah / Mezzah area, Damascus',
                'city' => 'Damascus',
                'location' => 'Al-Mouwasat University Hospital complex (Damascus)',
                'lat' => 33.5125000,
                'lon' => 36.2649400,
                'contact_phone' => '+963112133000',
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['emergency' => true, 'teaching_hospital' => true]),
                'website' => 'http://almouwasat.sy/',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'National University Hospital (formerly Al-Assad University Hospital)',
                'type' => 'medical',
                'address' => '17th April Street, Damascus',
                'city' => 'Damascus',
                'location' => 'National University Hospital — 17th April St, Damascus',
                'lat' => 33.5057160,
                'lon' => 36.2696350,
                'contact_phone' => '+963112126500',
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['teaching_hospital' => true, '24_7_emergency' => true]),
                'website' => 'http://www.nuhd.edu.sy',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Al-Bairouni University Hospital',
                'type' => 'medical',
                'address' => 'Harasta / Greater Damascus area (Al-Bairouni Complex)',
                'city' => 'Damascus (Harasta area)',
                'location' => 'Al-Bairouni University Hospital (oncology & pediatrics center)',
                'lat' => 33.5127100,
                'lon' => 36.2641600,
                'contact_phone' => '+963115359754',
                'contact_email' => 'buh@albaironi-hospital.sy',
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['oncology' => true, 'specialized' => true]),
                'website' => 'https://albairouni-hospital.sy/',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Al-Khawali (Al-Khawali Restaurant / Café area, Old City)',
                'type' => 'cafe',
                'address' => 'Maazanet Al-Shahem, Al-Salami Alley, Old City, Damascus',
                'city' => 'Damascus',
                'location' => 'Old City — Maazanet Al-Shahem area',
                'lat' => 33.5064000,
                'lon' => 36.3052000,
                'contact_phone' => '+963119797000',
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['traditional' => true, 'outdoor_seating' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Sheraton Aleppo Hotel',
                'type' => 'hotel',
                'address' => 'Al Khandaq Street, Bab Al-Faraj, Aleppo',
                'city' => 'Aleppo',
                'location' => 'Downtown / Bab Al-Faraj (near Aleppo Citadel)',
                'lat' => 36.2047200,
                'lon' => 37.1538900,
                'contact_phone' => '+96321114111',
                'contact_email' => 'info@nct.sy',
                'main_image' => null,
                'images' => null,
                'conditions' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 2 Beit Wakil (heritage house / guesthouse / restaurant) - Aleppo
            [
                'name' => 'Beit Wakil',
                'type' => 'restaurant',
                'address' => 'Old City, Aleppo (historic Beit Wakil)',
                'city' => 'Aleppo',
                'location' => 'Historic Old City — traditional Aleppine house (Beit Wakil)',
                'lat' => 36.2305000,
                'lon' => 37.1831110,
                'contact_phone' => null,
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['traditional' => true, 'entertainment' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 3 Beroea Restaurant (Aleppo)
            [
                'name' => 'Beroea Restaurant',
                'type' => 'restaurant',
                'address' => 'Central Aleppo (refer to local listings)',
                'city' => 'Aleppo',
                'location' => 'Aleppo city centre / near main attractions',
                'lat' => 36.2012400,
                'lon' => 37.1611700,
                'contact_phone' => null,
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['reservations' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 4 Cordoba Restaurant (Aleppo)
            [
                'name' => 'Cordoba Restaurant',
                'type' => 'restaurant',
                'address' => 'Aleppo (see local listings / Tripadvisor entry)',
                'city' => 'Aleppo',
                'location' => 'Aleppo — listed among popular restaurants',
                'lat' => 36.2012400,
                'lon' => 37.1611700,
                'contact_phone' => null,
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['lebanese_cuisine' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 5 Ikebana (Japanese / Sheraton Aleppo - restaurant)
            [
                'name' => 'Ikebana (Sheraton Aleppo - Japanese)',
                'type' => 'restaurant',
                'address' => 'Inside Sheraton Aleppo Hotel, Bab Al-Faraj, Aleppo',
                'city' => 'Aleppo',
                'location' => 'Sheraton Aleppo complex — hotel restaurant',
                'lat' => 36.2047200,
                'lon' => 37.1538900,
                'contact_phone' => '+96321114111',
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['reservations' => true, 'fine_dining' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 6 Bistro Aleppo (listed on TripAdvisor)
            [
                'name' => 'Bistro Aleppo',
                'type' => 'cafe',
                'address' => 'Aleppo central area (TripAdvisor listing)',
                'city' => 'Aleppo',
                'location' => 'Aleppo — popular bistro listed in travel guides',
                'lat' => 36.2012400,
                'lon' => 37.1611700,
                'contact_phone' => null,
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['outdoor_seating' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 7 Al-Baath University Hospital (Homs)
            [
                'name' => 'Al-Baath University Hospital',
                'type' => 'medical',
                'address' => 'Al-Baath University campus area, Homs',
                'city' => 'Homs',
                'location' => 'Homs — Al-Baath University Hospital (main university hospital)',
                'lat' => 34.7076640,
                'lon' => 36.7051650,
                'contact_phone' => '031-2113826',
                'contact_email' => 'HomsUniv.Hos@moh.gov.sy',
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['teaching_hospital' => true, 'emergency' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 8 Tishreen University Hospital (Latakia)
            [
                'name' => 'Tishreen University Hospital',
                'type' => 'medical',
                'address' => 'Tishreen University / Latakia University area, Latakia',
                'city' => 'Latakia',
                'location' => 'Latakia — Tishreen University Hospital (university medical complex)',
                'lat' => 35.5245700,
                'lon' => 35.8027100,
                'contact_phone' => '+96341554261',
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['university_hospital' => true, 'surgical_services' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9 National Hospital (Hama)
            [
                'name' => 'National Hospital (Hama)',
                'type' => 'medical',
                'address' => 'Hama — National Hospital (road to Homs)',
                'city' => 'Hama',
                'location' => 'Hama — main national hospital (regional referral centre)',
                'lat' => 35.1127780,
                'lon' => 36.7577780,
                'contact_phone' => '033-510936',
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['emergency' => true]),
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 10 Tartous National Hospital (Tartus)
            [
                'name' => 'Tartous National Hospital',
                'type' => 'medical',
                'address' => 'Tartus city — المستشفى الوطني بطرطوس',
                'city' => 'Tartus',
                'location' => 'Tartus — national hospital on the coastal governorate',
                'lat' => 34.8833330,
                'lon' => 35.8833330,
                'contact_phone' => null,
                'contact_email' => null,
                'main_image' => null,
                'images' => null,
                'conditions' => json_encode(['regional_referral' => true]),
                'website' => null,
                'facebook' => 'https://www.facebook.com/albasselhospital/',
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
