<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MinistriesSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $ministries = [
            [
                'name' => 'وزارة الشؤون الإدارية والتنمية',
                'description' => 'Ministry of Administrative Development',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الزراعة والإصلاح الزراعي',
                'description' => 'Ministry of Agriculture and Agrarian Reform',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الاتصالات وتكنولوجيا المعلومات',
                'description' => 'Ministry of Communications and Information Technology',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الثقافة',
                'description' => 'Ministry of Culture',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الدفاع',
                'description' => 'Ministry of Defense',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الاقتصاد والصناعة',
                'description' => 'Ministry of Economy and Industry',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة التربية والتعليم',
                'description' => 'Ministry of Education',
                'address' => 'دمشق',
                'location' => 'Damascus',
                'lat' => null,
                'lon' => null,
                'contact_phone' => '+963 11 3313205',
                'contact_email' => null,
                'website' => 'https://moed.gov.sy/',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الطوارئ وإدارة الكوارث',
                'description' => 'Ministry of Emergency and Disaster Management',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الأوقاف',
                'description' => 'Ministry of Endowments (Awqaf)',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الطاقة',
                'description' => 'Ministry of Energy',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة المالية',
                'description' => 'Ministry of Finance',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الخارجية والمغتربين',
                'description' => 'Ministry of Foreign Affairs and Expatriates',
                'address' => '17 April, Damascus, Syria',
                'location' => 'Damascus',
                'lat' => null,
                'lon' => null,
                'contact_phone' => '+963 11 218 1000',
                'contact_email' => 'contact@mofaex.gov.sy',
                'website' => 'https://mofaex.gov.sy/',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الصحة',
                'description' => 'Ministry of Health',
                'address' => 'Damascus',
                'location' => 'Damascus',
                'lat' => null,
                'lon' => null,
                'contact_phone' => '+963 11 3311020',
                'contact_email' => 'health-min@net.sy',
                'website' => 'https://www.moh.gov.sy/',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة التعليم العالي والبحث العلمي',
                'description' => 'Ministry of Higher Education and Scientific Research',
                'address' => 'Mezzeh, Damascus',
                'location' => 'Damascus',
                'lat' => null,
                'lon' => null,
                'contact_phone' => '+963 11 2119865',
                'contact_email' => 'mhe@mhe.gov.sy',
                'website' => 'https://www.mhe.gov.sy/',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الإعلام',
                'description' => 'Ministry of Information',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => 'complains@moi.gov.sy',
                'website' => 'https://moi.gov.sy/',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الداخلية',
                'description' => 'Ministry of Interior',
                'address' => 'Kafr Sousa, Damascus',
                'location' => 'Damascus',
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => 'http://moia.gov.sy/',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة العدل',
                'description' => 'Ministry of Justice',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الإدارة المحلية والبيئة',
                'description' => 'Ministry of Local Administration and Environment',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الأشغال العامة والإسكان',
                'description' => 'Ministry of Public Works and Housing',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الشؤون الاجتماعية والعمل',
                'description' => 'Ministry of Social Affairs and Labor',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة النقل',
                'description' => 'Ministry of Transport',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة السياحة',
                'description' => 'Ministry of Tourism',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'وزارة الشباب والرياضة',
                'description' => 'Ministry of Youth and Sports',
                'address' => null,
                'location' => null,
                'lat' => null,
                'lon' => null,
                'contact_phone' => null,
                'contact_email' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'linkedin' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('ministries')->insert($ministries);
    }
}
